// j2nodejs-12.h: 标准系统包含文件的包含文件
// 或项目特定的包含文件。

#pragma once

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_j2nodejs_NodeJS */

#ifndef _Included_com_j2nodejs_NodeJS
#define _Included_com_j2nodejs_NodeJS
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_j2nodejs_NodeJS
	 * Method:    nodeStart
	 * Signature: (Ljava/lang/String;)V
	 */
	JNIEXPORT void JNICALL Java_com_j2nodejs_NodeJS_nodeStart
	(JNIEnv*, jobject, jstring);
#ifdef __cplusplus
}
#endif
#endif
